server:
    port: 8080
    error:
        include-message: always
        include-binding-errors: always
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/demo
    config:
        import: db.yaml
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        show-sql: true


logging:
    level:
        org:
            springframework:
                web: DEBUG
            hibernate: ERROR
        net:
            guides: DEBUG